name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: tests-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  e2e:
    name: 'e2e tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Test
        run: mvn -B -U test

      - name: download testquality CLI
        run: | 
          curl http://cli.testquality.com/testquality-linux -o public
          pwd
          ls

      - name: Publish E2E Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ !cancelled() }}
        with:
          check_name: e2e test results
          files: ui-tests/target/*-reports/TEST-*.xml
          report_individual_runs: "true"

#      - name: Send to testquality
#        run:
